### ISSUE TITLE
zip2zim deos not start (anymore?)

### ISSUE THREAD

**Issue by kelson42** [openzim/zip2zim#2]
```
$ npm i && npm start
npm WARN zip2zim@1.0.0 No repository field.

added 285 packages in 2.345s

> zip2zim@1.0.0 start /home/kelson/code/zip2zim
> pm2 start index.ts --no-daemon

pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2017-11-18 14:33:00: Launching in no daemon mode
2017-11-18 14:33:00: [PM2][ERROR] Interpreter /home/kelson/code/zip2zim/node_modules/pm2/node_modules/.bin/ts-node does not seems to be available
2017-11-18 14:33:00: [PM2] Starting /home/kelson/code/zip2zim/index.ts in fork_mode (1 instance)
2017-11-18 14:33:00: Starting execution sequence in -fork mode- for app name:index id:0
2017-11-18 14:33:00: App name:index id:0 online
2017-11-18 14:33:00: Error: spawn /home/kelson/code/zip2zim/node_modules/pm2/node_modules/.bin/ts-node ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-11-18 14:33:00: [PM2] Done.
2017-11-18 14:33:00: ┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user   │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼────────┼──────────┤
│ index    │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0%  │ 0 B    │ kelson │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴────────┴──────────┘
2017-11-18 14:33:00:  Use `pm2 show <id|name>` to get more details about an app
2017-11-18 14:33:00: [--no-daemon] Continue to stream logs
2017-11-18 14:33:00: [--no-daemon] Exit on target PM2 exit pid=6989

$ node --version
v8.9.1
$ npm --version
5.5.1
```

**Comment by ISNIT0** [comment]
Fixed.
I've now added a build stage (rather than compiling on the fly in PM2)

I used to quite like PM2 for running typescript, but have since learned that it's not very reliable... Much better to compile first, then run JavaScript with PM2
